<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:oa="http://www.openapplications.org/oagis/9"
	xmlns="http://www.mimosa.org/ccom4"
	targetNamespace="http://www.mimosa.org/ccom4"
	elementFormDefault="qualified"
	attributeFormDefault="unqualified">

	<xs:import schemaLocation="../../oagis/Meta.xsd" namespace="http://www.openapplications.org/oagis/9"/>
	<xs:include schemaLocation="../CCOM.xsd"/>

	<xs:element name="ShowBreakdownStructures">
		<xs:annotation>
			<xs:documentation xml:lang="en">
Response returning 0 to N breakdown structures or the number of breakdown structures resulting from the request.
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="oa:BusinessObjectDocumentType">
					<xs:sequence>
						<xs:element name="DataArea">
							<xs:complexType>
								<xs:sequence>
									<xs:element ref="oa:Show"/>
									<xs:element name="Structures" minOccurs="0" maxOccurs="unbounded">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="Count" type="Count" minOccurs="0" maxOccurs="unbounded"/>
												<xs:element name="BreakdownStructure" type="BreakdownStructure" minOccurs="0" maxOccurs="unbounded"/>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

</xs:schema>
